const DummyData = [{
  posts:[
    { title : 'திரைத்துறை போஸ்ட் புரடக்சன் பணிகளுக்கு அனுமதி', content: '<p>திரைத்துறை மற்றும் சின்னத்திரை தயாரிப்பாளர்களின் கோரிக்கையை ஏற்று போஸ்ட் புரடக்சன் பணிகளுக்கு தமிழக அரசு அனுமதி அளித்துள்ளது.</p>', categories: '2,4,5', tags: 'cinema, corona', brands: '1,2', featured_img: '/uploads/images/postproduction.jpg', created_by: 1, created_at: new Date(), updated_at: new Date() },
    { title : 'விளையாட்டு நடவடிக்கைகள்', content: '<p>திரைத்துறை மற்றும் சின்னத்திரை தயாரிப்பாளர்களின் கோரிக்கையை ஏற்று போஸ்ட் புரடக்சன் பணிகளுக்கு தமிழக அரசு அனுமதி அளித்துள்ளது.</p>', categories: '1,2,6', tags: 'cinema, corona', brands: '6', featured_img: 'https://kaalaimani.com/wp-content/uploads/2020/04/shops.jpg', created_by: 1, created_at: new Date(), updated_at: new Date() },
    { title : 'கோவிட்-19 மேலாண்மைக்கான தேசிய அளவிலான உத்தரவுகள்', content: '<p>திரைத்துறை மற்றும் சின்னத்திரை தயாரிப்பாளர்களின் கோரிக்கையை ஏற்று போஸ்ட் புரடக்சன் பணிகளுக்கு தமிழக அரசு அனுமதி அளித்துள்ளது.</p>', categories: '2', tags: 'cinema, corona', brands: '1', featured_img: 'https://kaalaimani.com/wp-content/uploads/2020/04/mutations-of-the-coronavirus-794x510.jpg', created_by: 1, created_at: new Date(), updated_at: new Date() },
    { title : 'எந்தெந்த மண்டலங்களில் மாநிலங்கள் முடிவு செய்யலாம்?', content: '<p>திரைத்துறை மற்றும் சின்னத்திரை தயாரிப்பாளர்களின் கோரிக்கையை ஏற்று போஸ்ட் புரடக்சன் பணிகளுக்கு தமிழக அரசு அனுமதி அளித்துள்ளது.</p>', categories: '5', tags: 'cinema, corona', brands: '2', featured_img: 'https://kaalaimani.com/wp-content/uploads/2020/05/redzone.png', created_by: 1, created_at: new Date(), updated_at: new Date() },
    { title : 'பொது முடக்கம் மே 31 வரை நீட்டிப்பு', content: '<p>திரைத்துறை மற்றும் சின்னத்திரை தயாரிப்பாளர்களின் கோரிக்கையை ஏற்று போஸ்ட் புரடக்சன் பணிகளுக்கு தமிழக அரசு அனுமதி அளித்துள்ளது.</p>', categories: '4', tags: 'cinema, corona', brands: '3', featured_img: 'https://kaalaimani.com/wp-content/uploads/2020/04/lockdown-full.jpg', created_by: 1, created_at: new Date(), updated_at: new Date() },
    { title : 'அப்பள தயாரிப்பு தொழிலாளர்களுக்கு வணிகர் நல வாரியத்தின் மூலம் நிவாரணம் வழங்க வேண்டும்', content: '<p>திரைத்துறை மற்றும் சின்னத்திரை தயாரிப்பாளர்களின் கோரிக்கையை ஏற்று போஸ்ட் புரடக்சன் பணிகளுக்கு தமிழக அரசு அனுமதி அளித்துள்ளது.</p>', categories: '5', tags: 'cinema, corona', brands: '4', featured_img: 'https://kaalaimani.com/wp-content/uploads/2020/05/appalam-making.jpg', created_by: 1, created_at: new Date(), updated_at: new Date() },
    { title : 'ஒபாமாவுக்கு எந்தத் திறனும் இல்லை சொல்கிறார் டிரம்ப்', content: '<p>திரைத்துறை மற்றும் சின்னத்திரை தயாரிப்பாளர்களின் கோரிக்கையை ஏற்று போஸ்ட் புரடக்சன் பணிகளுக்கு தமிழக அரசு அனுமதி அளித்துள்ளது.</p>', categories: '1', tags: 'cinema, corona', brands: '5', featured_img: 'https://kaalaimani.com/wp-content/uploads/2020/04/TRUMP-WHO-825x510.jpg', created_by: 1, created_at: new Date(), updated_at: new Date() },
    { title : 'ஃபேஸ்புக் கைக்கு போன ஜிஃப் நிறுவனம்', content: '<p>திரைத்துறை மற்றும் சின்னத்திரை தயாரிப்பாளர்களின் கோரிக்கையை ஏற்று போஸ்ட் புரடக்சன் பணிகளுக்கு தமிழக அரசு அனுமதி அளித்துள்ளது.</p>', categories: '1,6', tags: 'cinema, corona', brands: '6', featured_img: 'https://kaalaimani.com/wp-content/uploads/2020/03/FB-825x510.jpg', created_by: 1, created_at: new Date(), updated_at: new Date() },
    { title : 'பே டிஎம் நிறுவனம் அறிமுகம் வயதானவர்களை தேடி வாசலுக்கு வரும் பணம்', content: '<p>திரைத்துறை மற்றும் சின்னத்திரை தயாரிப்பாளர்களின் கோரிக்கையை ஏற்று போஸ்ட் புரடக்சன் பணிகளுக்கு தமிழக அரசு அனுமதி அளித்துள்ளது.</p>', categories: '2', tags: 'cinema, corona', brands: '5', featured_img: 'https://kaalaimani.com/wp-content/uploads/2020/05/paytm.jpg', created_by: 1, created_at: new Date(), updated_at: new Date() },
    { title : 'இயர்பட்ஸ் வடிவில் ஒன்பிளஸ் ட்ரூ வயர்லஸ் இயர்பட்ஸ்', content: '<p>திரைத்துறை மற்றும் சின்னத்திரை தயாரிப்பாளர்களின் கோரிக்கையை ஏற்று போஸ்ட் புரடக்சன் பணிகளுக்கு தமிழக அரசு அனுமதி அளித்துள்ளது.</p>', categories: '3', tags: 'cinema, corona', brands: '3', featured_img: 'https://kaalaimani.com/wp-content/uploads/2020/05/one-plus-earbuds.png', created_by: 1, created_at: new Date(), updated_at: new Date() },
    { title : 'மே 31 வரை ஏர் இந்தியா உள்நாட்டு விமான சேவை இல்லை', content: '<p>திரைத்துறை மற்றும் சின்னத்திரை தயாரிப்பாளர்களின் கோரிக்கையை ஏற்று போஸ்ட் புரடக்சன் பணிகளுக்கு தமிழக அரசு அனுமதி அளித்துள்ளது.</p>', categories: '1', tags: 'cinema, corona', brands: '5', featured_img: 'https://kaalaimani.com/wp-content/uploads/2019/12/air-india.jpg', created_by: 1, created_at: new Date(), updated_at: new Date() },
  ],
  pdfs:[
    { title: 'சென்னை சிறுவன்', description: 'ஆங்கில தட்டச்சு வழியாக நம் மொழி', categories: '1,2', brands: '1', tags: 'pdf, news', featured_img: 'http://saadhanai.com/wp-content/uploads/2019/03/saadhanai-1.jpg', url: 'http://saadhanai.com/wp-content/uploads/2019/03/saadhanai.com-ARRS-18.03.2019.pdf', created_by: '1', created_at: new Date(), updated_at: new Date() },
    { title: 'என்பது ஆறு வயதில் நாற்பத்தி மூன்று கிலோமீட்டர் ', description: 'ஆங்கில தட்டச்சு வழியாக நம் மொழி', categories: '3', brands: '2', tags: 'pdf, news', featured_img: 'http://saadhanai.com/wp-content/uploads/2019/03/saadhanai.jpg', url: 'http://saadhanai.com/wp-content/uploads/2019/03/saadhanai.com-SVV-04.03.2019.pdf', created_by: '1', created_at: new Date(), updated_at: new Date() },
    { title: 'மார்வெல்ஸ் ஹீரோக்களை உருவாக்கிய ஸ்டான் லீ ', description: 'ஆங்கில தட்டச்சு வழியாக நம் மொழி', categories: '1,4', brands: '3', tags: 'pdf, news', featured_img: 'http://saadhanai.com/wp-content/uploads/2019/03/saadhanai.jpg', url: 'http://saadhanai.com/wp-content/uploads/2019/02/saadhanai.com-ARRS-18.02.2019.pdf', created_by: '1', created_at: new Date(), updated_at: new Date() },
    { title: 'படிப்பு குறைவு பட்டம் அதிகம்', description: 'ஆங்கில தட்டச்சு வழியாக நம் மொழி', categories: '2,5', brands: '4', tags: 'pdf, news', featured_img: 'http://saadhanai.com/wp-content/uploads/2019/02/saadhanai-4-2-19.jpg', url: 'http://saadhanai.com/wp-content/uploads/2019/02/saadhanai.com-SVV-04.02.2019-1.pdf', created_by: '1', created_at: new Date(), updated_at: new Date() },
    { title: 'நஜநாயகத்தை கடைகோடிக்கும் கொண்டு சென்றவர் ', description: 'ஆங்கில தட்டச்சு வழியாக நம் மொழி', categories: '5', brands: '5', tags: 'pdf, news', featured_img: 'http://saadhanai.com/wp-content/uploads/2019/01/saadhanai.com-SVV-21.01.2019-pdf.jpg', url: 'http://saadhanai.com/wp-content/uploads/2019/01/saadhanai.com-SVV-21.01.2019.pdf', created_by: '1', created_at: new Date(), updated_at: new Date() },
    { title: 'வாழலும் சுதந்திர போராட்ட தியாகி', description: 'ஆங்கில தட்டச்சு வழியாக நம் மொழி', categories: '3', brands: '6', tags: 'pdf, news', featured_img: 'http://saadhanai.com/wp-content/uploads/2019/01/saadhanai.com-SGS-07.01.2019-pdf.jpg', url: 'http://saadhanai.com/wp-content/uploads/2019/01/saadhanai.com-SGS-07.01.2019.pdf', created_by: '1', created_at: new Date(), updated_at: new Date() },
    { title: 'கோடிகளை தோட்ட சந்தோஷ்', description: 'ஆங்கில தட்டச்சு வழியாக நம் மொழி', categories: '2,4', brands: '2', tags: 'pdf, news', featured_img: 'http://saadhanai.com/wp-content/uploads/2018/12/saadhanai.com-SGS-24.12.2018-pdf.jpg', url: 'http://saadhanai.com/wp-content/uploads/2018/12/saadhanai.com-SGS-24.12.2018.pdf', created_by: '1', created_at: new Date(), updated_at: new Date() },
    { title: 'அன்று மெக்கானிக் இன்று உகலகத்தின் உயர்ந்த', description: 'ஆங்கில தட்டச்சு வழியாக நம் மொழி', categories: '2', brands: '1', tags: 'pdf, news', featured_img: 'http://saadhanai.com/wp-content/uploads/2018/12/saadhanai-10-12-18.jpg', url: 'http://saadhanai.com/wp-content/uploads/2018/12/saadhanai.com-ARRS-10.12.2018.pdf', created_by: '1', created_at: new Date(), updated_at: new Date() },
    { title: 'அகராதி சாதனை', description: 'ஆங்கில தட்டச்சு வழியாக நம் மொழி', categories: '1', brands: '3', tags: 'pdf, news', featured_img: 'http://saadhanai.com/wp-content/uploads/2018/11/saadhanai.com-26.jpg', url: 'http://saadhanai.com/wp-content/uploads/2018/11/saadhanai.com-26.11.2018-SVV.pdf', created_by: '1', created_at: new Date(), updated_at: new Date() },
    { title: 'முப்பதாவது மலையேற்றம் நூறாவது பிறந்தநாள்', description: 'ஆங்கில தட்டச்சு வழியாக நம் மொழி', categories: '6', brands: '4', tags: 'pdf, news', featured_img: 'http://saadhanai.com/wp-content/uploads/2019/04/sadhanai-Apr-01042019-A-pdf.jpg', url: 'http://saadhanai.com/wp-content/uploads/2019/01/saadhanai.com-SVV-21.01.2019.pdf', created_by: '1', created_at: new Date(), updated_at: new Date() },
  ],
  videos:[
    { title: 'பிக் பக் பின்னி', description: 'ஆங்கில தட்டச்சு வழியாக நம் மொழி', categories: '1', brands: '1', tags: 'video, news', featured_img: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/BigBuckBunny.jpg', url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4', created_by: '1', created_at: new Date(), updated_at: new Date() },
    { title: 'தி பிரஸ்ட் ப்ளெண்டர் ஓபன் மொவயே பிரேம்', description: 'ஆங்கில தட்டச்சு வழியாக நம் மொழி', categories: '2', brands: '2', tags: 'video, news', featured_img: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ElephantsDream.jpg', url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4', created_by: '1', created_at: new Date(), updated_at: new Date() },
    { title: 'ஹபா கோ நொவ் ஒர்க்ஸ் வித் கிரோமேசஷ்டி', description: 'ஆங்கில தட்டச்சு வழியாக நம் மொழி', categories: '3', brands: '3', tags: 'video, news', featured_img: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerBlazes.jpg', url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', created_by: '1', created_at: new Date(), updated_at: new Date() },
    { title: 'இன்றோடுசிங் கிரோமேசஷ்டி', description: 'ஆங்கில தட்டச்சு வழியாக நம் மொழி', categories: '4', brands: '4', tags: 'video, news', featured_img: '', url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerEscapes.jpg', created_by: '1', created_at: new Date(), updated_at: new Date() },
    { title: 'தி ஏசிஎஸ்ட் வாய் டு என்ஜோய் ஒன்லைன் வீடியோ அண்ட் மியூசிக்', description: 'ஆங்கில தட்டச்சு வழியாக நம் மொழி', categories: '5', brands: '5', tags: 'video, news', featured_img: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerFun.jpg', url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4', created_by: '1', created_at: new Date(), updated_at: new Date() },
    { title: 'ஒன யுவர் டிவி—போர் தி டைம்ஸ் தட் கால்', description: 'ஆங்கில தட்டச்சு வழியாக நம் மொழி', categories: '6', brands: '6', tags: 'video, news', featured_img: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerJoyrides.jpg', url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4', created_by: '1', created_at: new Date(), updated_at: new Date() },
    { title: 'லேஅர்ன் ஹொவ் டு உஸ் கிரோமேசஷ்டி வித் நெட்டபிலிஸ்', description: 'ஆங்கில தட்டச்சு வழியாக நம் மொழி', categories: '7', brands: '1', tags: 'video, news', featured_img: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/ForBiggerMeltdowns.jpg', url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4', created_by: '1', created_at: new Date(), updated_at: new Date() },
    { title: 'சின்டெல் ஐஸ் அந்த இன்டெபேன்டென்டலி ப்ரோட்ஸ்ட் சோர்ட் பிலிம்', description: 'ஆங்கில தட்டச்சு வழியாக நம் மொழி', categories: '8', brands: '2', tags: 'video, news', featured_img: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/Sintel.jpg', url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4', created_by: '1', created_at: new Date(), updated_at: new Date() },
    { title: 'ஸ்மோக்கிங் டிரே டேக்ஸ் தி ஆல்-நியூ சுப்ரு', description: 'ஆங்கில தட்டச்சு வழியாக நம் மொழி', categories: '9', brands: '3', tags: 'video, news', featured_img: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/SubaruOutbackOnStreetAndDirt.jpg', url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4', created_by: '1', created_at: new Date(), updated_at: new Date() },
    { title: 'ஏர்ஸ் ஒப்பி ஸ்டீல் வாஸ் ரீலீஸிட்', description: 'ஆங்கில தட்டச்சு வழியாக நம் மொழி', categories: '1', brands: '4', tags: 'video, news', featured_img: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/images/TearsOfSteel.jpg', url: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4', created_by: '1', created_at: new Date(), updated_at: new Date() },
  ]
}];

module.exports = DummyData;